"""add data sources and data source connections

Revision ID: ae4daa14818c
Revises: 4ad448924478
Create Date: 2026-08-13 17:42:54.234593
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ae4daa14818c"
down_revision: Union[str, Sequence[str], None] = "4ad448924478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "POSTGRESQL",
                "MYSQL",
                "CSV",
                "EXCEL",
                "GOOGLE_SHEETS",
                "REST_API",
                name="data_source_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ERROR", name="data_source_status"),
            server_default="INACTIVE",
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name="ck_data_sources_name_not_empty"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_sources_created_by"), "data_sources", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_data_sources_workspace_id"),
        "data_sources",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "data_source_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), server_default="5432", nullable=False),
        sa.Column("database_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("encrypted_password", sa.String(length=1024), nullable=False),
        sa.Column(
            "ssl_mode", sa.String(length=32), server_default="prefer", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_sources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "data_source_id", name="uq_data_source_connections_data_source_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_source_connections")
    op.drop_index(op.f("ix_data_sources_workspace_id"), table_name="data_sources")
    op.drop_index(op.f("ix_data_sources_created_by"), table_name="data_sources")
    op.drop_table("data_sources")
    sa.Enum(name="data_source_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="data_source_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
