"""Stable MCP error codes and categories.

Machine-readable values for safe client responses. Do not use raw Python
exception class names as API error codes.
"""

from __future__ import annotations

from enum import Enum


class MCPErrorCategory(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    RATE_LIMITED = "RATE_LIMITED"
    QUERY_ERROR = "QUERY_ERROR"
    QUERY_TIMEOUT = "QUERY_TIMEOUT"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    DATA_SOURCE_ERROR = "DATA_SOURCE_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class MCPErrorCode(str, Enum):
    MCP_SERVER_NOT_FOUND = "MCP_SERVER_NOT_FOUND"
    MCP_TOOL_NOT_FOUND = "MCP_TOOL_NOT_FOUND"
    MCP_TOOL_VALIDATION_FAILED = "MCP_TOOL_VALIDATION_FAILED"
    MCP_UNAUTHORIZED = "MCP_UNAUTHORIZED"
    MCP_FORBIDDEN = "MCP_FORBIDDEN"
    MCP_DATA_SOURCE_NOT_FOUND = "MCP_DATA_SOURCE_NOT_FOUND"
    MCP_DATA_SOURCE_ACCESS_DENIED = "MCP_DATA_SOURCE_ACCESS_DENIED"
    MCP_RATE_LIMITED = "MCP_RATE_LIMITED"
    MCP_QUERY_INVALID = "MCP_QUERY_INVALID"
    MCP_QUERY_TIMEOUT = "MCP_QUERY_TIMEOUT"
    MCP_QUERY_LIMIT_EXCEEDED = "MCP_QUERY_LIMIT_EXCEEDED"
    MCP_RESULT_LIMIT_EXCEEDED = "MCP_RESULT_LIMIT_EXCEEDED"
    MCP_DATABASE_UNAVAILABLE = "MCP_DATABASE_UNAVAILABLE"
    MCP_DATABASE_ERROR = "MCP_DATABASE_ERROR"
    MCP_SAMPLE_DATA_ERROR = "MCP_SAMPLE_DATA_ERROR"
    MCP_RESOURCE_NOT_FOUND = "MCP_RESOURCE_NOT_FOUND"
    MCP_CONFIGURATION_ERROR = "MCP_CONFIGURATION_ERROR"
    MCP_SERVER_ERROR = "MCP_SERVER_ERROR"
    MCP_INTERNAL_ERROR = "MCP_INTERNAL_ERROR"
